- name: uconsole bootstrap
  hosts: uconsole
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: akos
        state: present
        key: "{{ lookup('file', '/Users/akosmelczer/.ssh/id_rsa.pub') }}"

    - name: apt install packages
      become: true
      apt:
        update_cache: true
        name:
          - git
          - stow
          - waybar
          - tofi
        state: latest

